### PR TITLE
Panel Icons

### PR DESCRIPTION
**Pull request by JOSE89**
###Defect Fixes
When submitting a PR, please also create an issue documenting the error.

###Feature Requests
Due to company policy, we are unable to accept feature request PRs with significant changes as such cases has to be implemented by our team following our own processes.
Smaller scaled feature implementations such as adding a property to a component will be considered for merging.

### CODE REVIEW

**Comment by JOSE89** [comment]
I've done the PR!

**Comment by CylonOven** [comment]
PR is for issue #888

**Comment by CylonOven** [comment]
Looking at the commits, I have a feeling that they're not going to accept them.
You've changed quite a bit including things in their package.json. 
If you want any PR to be accpeted in any repo you should have the changes clear and to the point.
Changing some minor formating such as `{foobar}` to `{ foobar }` and other things makes it harder for them to review and less likely to accept.

**Comment by JOSE89** [comment]
PR Panel Icons without spaces #893

**Pull request closed without merging**
