### PR TITLE
Fix #3200 Add Generics to Dropdown, Cascadeselect, Listbox, Multiselect, Selectbutton

### LINKED ISSUE #3200: TypeScript: generic options support
Add generic typing to `SelectItem` type components:

- [x] cascadeselect.d.ts
- [x] dropdown.d.ts
- [x] listbox.d.ts
- [x] multiselect.d.ts
- [x] selectbutton.d.ts

### PR DESCRIPTION
**Pull request by DerDorius**
This Pull Request adds Generic Typing to these Files:
cascadeselect.d.ts
dropdown.d.ts
listbox.d.ts
multiselect.d.ts
selectbutton.d.ts

This Provides a better **Autocomplete** in the IDE as Mentioned in Issue https://github.com/primefaces/primereact/issues/3200

### CODE REVIEW

**Comment by melloware** [comment]
I absolutely love this.  I am letting the automated build run now to validate.

**Comment by melloware** [comment]
I created and linked new issue #3200

**Comment by melloware** [comment]
Sorry had to revert this.  ithink there is still a lot of work to do I was trying to make your generics work with `SelectButton` and it was not working.

SelectButton still defines `value: any` and then has issues with `itemTemplate?(option: any): React.ReactNode;` because it thinks the option is a `string when its needs to be a `selectitem.

To test just run `npm run dev` and change /selectbutton/index.js to selectbutton/index.tsx and you will see all the issues.

**Comment by DerDorius** [comment]
Thanks for Rewiewing 

Can you tell me exactly how to reproduce that, because the `itemTemplate` on my Fork has the correct types for all 3 Examples:
image

`value` has to bie `any`, because if i would type it with the generic  this error appears:
image

Because the `value` type is defined in the React.InputHTMLAtributes

**Comment by melloware** [comment]
OK in your branch drop this `index.tsx` in `\pages\selectbutton\index.js`

```ts
import Head from 'next/head';
import { useState } from 'react';
import { DocActions } from '../../components/doc/common/docactions';
import SelectButtonDoc from '../../components/doc/selectbutton';
import { SelectButton } from '../../components/lib/selectbutton/SelectButton';
import { SelectItem } from '../../components/lib/selectitem/selectitem';

const SelectButtonDemo = () => {
    const [value1, setValue1] = useState('Off');
    const [value2, setValue2] = useState<string>();
    const [value3, setValue3] = useState<string>();
    const options = ['Off', 'On'];
    const paymentOptions = [
        { label: 'Option 1', value: 1 },
        { label: 'Option 2', value: 2 },
        { label: 'Option 3', value: 3 }
    ] as SelectItem[];
    const justifyOptions = [
        { icon: 'pi pi-align-left', value: 'left' },
        { icon: 'pi pi-align-right', value: 'Right' },
        { icon: 'pi pi-align-center', value: 'Center' },
        { icon: 'pi pi-align-justify', value: 'Justify' }
    ] as SelectItem[];

    const justifyTemplate = (option) => {
        return <i className={option.icon as string}></i>;
    };

    return (
        <div>
            <Head>
                <title>React SelectButton Component</title>
                <meta name="description" content="SelectButton is used to choose single or multiple items from a list using buttons." />
            </Head>
            <div className="content-section introduction">
                <div className="feature-intro">
                    <h1>SelectButton</h1>
                    <p>SelectButton is used to choose single or multiple items from a list using buttons.</p>
                </div>

                <DocActions github="selectbutton/index.js" />
            </div>

            <div className="content-section implementation">
                <div className="card">
                    <h5>Single Selection</h5>
                    <SelectButton value={value1} options={options} onChange={(e) => setValue1(e.value)} />

                    <h5>Multiple Selection</h5>
                    <SelectButton value={value2} options={paymentOptions} onChange={(e) => setValue2(e.value)} optionLabel="name" multiple />

                    <h5>Custom Content</h5>
                    <SelectButton value={value3} options={justifyOptions} onChange={(e) => setValue3(e.value)} itemTemplate={justifyTemplate} optionLabel="value" />
                </div>
            </div>

            <SelectButtonDoc />
        </div>
    );
};

export default SelectButtonDemo;
```

I see these errors:
image

image

**Comment by melloware** [comment]
For example to make it all work above I had to change the signature and `value` to this..

```ts
export interface SelectButtonProps<TOption> extends Omit<React.DetailedHTMLProps<React.InputHTMLAttributes<HTMLDivElement>, HTMLDivElement>, 'value' | 'unselectable' | 'onChange' | 'ref'> {
    value?: string | number | ReadonlyArray<string> | ReadonlyArray<number> | TOption | ReadonlyArray<TOption> | undefined;
```

**Pull request merged**
