### PR TITLE
fix/#6144 htmlFor prop doesn't work in MultiStateCheckBox

### PR DESCRIPTION
**Pull request by charithAmila**
### Defect Fixes
Fix: #6144 htmlFor prop doesn't work in  MultiStateCheckBox

### CODE REVIEW

**Comment by melloware** [comment]
Did you check if PrimeVue has the same issue or has the same
Solution?

**Comment by melloware** [comment]
It looks like more than just this label is broken on the showcase the MultiState checkbox doesn't ever seem to get checked?

**Review by melloware — CHANGES_REQUESTED** [review]
I htink we need to investigate why the icons are not appearing also.

**Comment by charithAmila** [comment]
I will take a look.

**Comment by charithAmila** [comment]
> I htink we need to investigate why the icons are not appearing also.

The icons do not appear because both the background and icon colors are same. 

Dark mode preview:
Screen Shot 2024-03-21 at 11 30 42 AM

Suggestion: 
We should add a default color to the icon or parent element (div)

Results:
1. Added primary color to the parent element.
Screen Shot 2024-03-21 at 11 17 35 AM

2. Added primary color to the icon.
Screen Shot 2024-03-21 at 11 23 47 AM

**Comment by melloware** [comment]
OK I fixed the icons in my PR: https://github.com/primefaces/primereact/pull/6209

**Review by melloware — APPROVED** [review]

**Comment by mertsincan** [comment]
Hi,

Similar to https://github.com/primefaces/primereact/pull/6210#issuecomment-2017517413

We'll have added new structures for the next version. For now, closed. Thanks a lot for your PR!

**Pull request closed without merging**
