### PR TITLE
Feat: show tiled background for images with transparency in image preview

### PR DESCRIPTION
**Pull request by ecstrema**
Goes with #4541

### CODE REVIEW

**Comment by ecstrema** [comment]
The tiled background looks like this: 

image

**Comment by melloware** [comment]
@ecstrema i wonder if we should open a new issue ticket.  Then I think what we can do is add a new property like `transparent=true/false` to the Image so it would add this transparency with an additional style...

```css
.p-image-preview .p-image-transparent {
    background: #eee
        url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="400" height="400" fill-opacity=".25" ><rect x="200" width="200" height="200" /><rect y="200" width="200" height="200" /></svg>');
    background-size: 15px 15px;
}
```

**Comment by ecstrema** [comment]
Yup, that would probably be better to avoid breaking changes. 

We could also show a transparency toggle among the other actions (rotate, zoom, and close). But for all images with a background, it would do nothing which could be incomprehensible for users.

**Comment by melloware** [comment]
Going to close this for now.

**Pull request closed without merging**
