### PR TITLE
Fix #3373: Datatable show filter active

### LINKED ISSUE #3373: DataTable: custom filter icon is not updating
Continuation of : https://github.com/primefaces/primereact/issues/2976

cc @t-works  @jnlinn @bhkangw

### PR DESCRIPTION
**Pull request by melloware**
### Defect Fixes
Fix #3373: Datatable show filter active

### CODE REVIEW

**Comment by gem-hiteshahuja** [comment]
@melloware  Hey I am facing the same issue with the latest version i.e. 8.6.1.
Issue :
I am using onFilter event for filtering to catch the filter object after filtering is done. But this is not updating the filter icon to active/not adding any active class.

Can you please confirm if this issue is resolved from your side? If yes, can you please confirm the released version for this?

**Comment by melloware** [comment]
This will be fixed in 8.6.2 which is not released yet.

**Comment by gem-hiteshahuja** [comment]
@melloware 
Can you please tell in how many days we can expect the release of v8.6.2?

**Comment by melloware** [comment]
I don't work for PrimeTek just an open source volunteer but if you look at the release cadence of previous releases you can see PrimeTek releases about once a month.

**Pull request merged**
