### PR TITLE
Fix #6733: add null check condition in getOptionValue(Dropdown)

### LINKED ISSUE #6733: Dropdown: { value: 0 } doesn't work properly
### Describe the bug

If you use Dropdown options with `{ value: 0 }`, it doesn't work.

```jsx
<Dropdown
  value={0},
  options={[
    { label: '0', value: 0 },
    { label: '1', value: 1 },
    { label: '2', value: 2 }
  ]}
/>
```

### Reproducer

https://stackblitz.com/edit/vitejs-vite-5esx3k?file=src%2FApp.jsx,package.json&terminal=dev

### PrimeReact version

10.6.4 or higher

### React version

18.x

### Language

ALL

### Build / Runtime

Vite

### Browser(s)

_No response_

### Steps to reproduce the behavior

1. Go to the reproducer.
2. Check you can't see the `0` label.
3. Change the value to other one.
4. Change the value to `0` again.

### Expected behavior

`{ value: 0 }` works as an option.

### PR DESCRIPTION
**Pull request by KumJungMin**
### Defect Fixes
- fix #6733
- example: https://stackblitz.com/edit/vitejs-vite-5esx3k?file=src%2FApp.jsx,package.json&terminal=dev
스크린샷 2024-07-01 15 18 42

<br/><br/>

#### 1. add null check
- when default value is 0, the selected option is not selected
- the `resolveFieldData` function returns null if the value is not found, so we need to check if the value is not null :)
```js
// before
const getOptionValue = (option) => {
	return props.optionValue ? ObjectUtils.resolveFieldData(option, props.optionValue) : ObjectUtils.resolveFieldData(option, 'value') || option;
};
```
```js
// after

const getOptionValue = (option) => {
    if (props.optionValue) {
        return ObjectUtils.resolveFieldData(option, props.optionValue);
    } else {
        const dataValue = ObjectUtils.resolveFieldData(option, 'value');
        return dataValue !== null ? dataValue : option; // null checking!
    }
};
```

<br/>

#### 2. fix wrong check condition
- `hasSelectedOption` is function.
```js
const hasSelectedOption = () => {
    return ObjectUtils.isNotEmpty(props.value);
};
```

<br/>

- I changed `hasSelectedOption` to `hasSelectedOption()` to ensure the condition evaluates the result of the function call rather than a function reference.

```js
// before
const findSelectedOptionIndex = () => {
    return hasSelectedOption ? visibleOptions.findIndex((option) => isValidSelectedOption(option)) : -1;
};
```

```js
// after 
const findSelectedOptionIndex = () => {
    return hasSelectedOption() ? visibleOptions.findIndex((option) => isValidSelectedOption(option)) : -1;
};

```

<br/>

### result

https://github.com/primefaces/primereact/assets/37934668/3e4c5e13-0880-49e5-b6c1-e265cecfff3f

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by nitrogenous** [comment]
Thank you for your patience during our national vacation. We encountered and resolved an issue with getOptionValue and getOptionLabel reported by one of our PRO users. We prioritized fixing this problem as soon as possible before reviewing GitHub issues.

We appreciate your contribution and would like to ask you to check the latest version of the master branch to see if everything works fine for you as well.

Thank you for your support and understanding.

**Comment by nitrogenous** [comment]
Thank you for your patience during our national vacation. We encountered and resolved an issue with getOptionValue and getOptionLabel reported by one of our PRO users. We prioritized fixing this problem as soon as possible before reviewing GitHub issues.

We appreciate your contribution and would like to ask you to check the latest version of the master branch to see if everything works fine for you as well.

Thank you for your support and understanding. @KumJungMin

**Comment by KumJungMin** [comment]
@nitrogenous thank you for check the PR :)
I was check the issue, and the issue resolved this PR 😃

**Comment by KumJungMin** [comment]
@nitrogenous 
Oh Sorry, I just checked wrong. I checked again and this issue was resolved in master.
thank you for comment!

**Comment by melloware** [comment]
safe to close this PR and ticket?

**Comment by nitrogenous** [comment]
> @nitrogenous Oh Sorry, I just checked wrong. I checked again and this issue was resolved in master. thank you for comment!

I wish I had seen your pull request before. I am really sorry that we couldn't merge your PR. I would love to see your further contributions. Thank you for your support to our community

**Comment by KumJungMin** [comment]
@nitrogenous 
I'm glad the issue was resolved quickly.
Even though it wasn't merged, it was nice to be able to read a lot of the code while trying to contribute!
Thank you again for your comment. Have a nice day 😄

**Pull request closed without merging**
