### PR TITLE
Fix #3171: ScrollPanel Cannot scroll inside dialog 

### LINKED ISSUE #3171: ScrollPanel: Cannot scroll inside dialog
### Describe the bug

Vertical scroll in ScrollPanel doesn't work when I would like move it with a cursor.

### Reproducer

https://codesandbox.io/s/beautiful-http-wmb3ut?file=/src/App.js

### PrimeReact version

8.4.0

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome

### Steps to reproduce the behavior

_No response_

### Expected behavior

When I grab vertical scroll in a ScrollPanel, I can move it.

### PR DESCRIPTION
**Pull request by habubey**
### Defect Fixes
Fixed bugs when converting from class comp. to functional comp.

### CODE REVIEW

**Review by mertsincan — APPROVED** [review]

**Comment by mertsincan** [comment]
@habubey please resolve conflicts ;)

**Comment by melloware** [comment]
I just fixed the conflict :)

**Comment by melloware** [comment]
Build is rerunning now

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
OK just need to run `npm run format` on it to format it.

**Comment by habubey** [comment]
> OK just need to run `npm run format` on it to format it.

Working on it ✅

**Pull request merged**
