### PR TITLE
Treeselect resolution for node ids equals to 0 

### PR DESCRIPTION
**Pull request by flashboss**
###Defect Fixes
When submitting a PR, please also create an issue documenting the error.

###Feature Requests
Due to company policy, we are unable to accept feature request PRs with significant changes as such cases has to be implemented by our team following our own processes.
Smaller scaled feature implementations such as adding a property to a component will be considered for merging.

### CODE REVIEW

**Comment by flashboss** [comment]
It resolves the bug identified by https://github.com/primefaces/primereact/issues/2372

**Comment by melloware** [comment]
I think you can do this...

```javascript
if (ObjectUtils.isNotEmpty(this.props.value) && this.props.options) {
```

PrimeReact has that custom ObjecUtils method which specifically does not look for `0` as falsy.

**Review by melloware — CHANGES_REQUESTED** [review]
see my comment

**Comment by flashboss** [comment]
good

**Review by melloware — APPROVED** [review]

**Comment by mertsincan** [comment]
Nice teamwork! Thanks a lot for your contribution!

Best Regards,

**Pull request merged**
