### PR TITLE
Fix #3546: Splitter error with only 1 panel

### LINKED ISSUE #3546: Splitter: Error with only 1 panel
In PrimeReact 8.7.1, the default Splitter + SplitterPanel is throwing a "Cannot read properties of undefined (reading 'props')" error:

```js
splitter.esm.js:142 Uncaught TypeError: Cannot read properties of undefined (reading 'props')
    at panelSize (splitter.esm.js:142:1)
    at createPanel (splitter.esm.js:362:1)
    at react.development.js:1158:1
    at mapIntoArray (react.development.js:1049:1)
    at Object.mapChildren [as map] (react.development.js:1157:1)
    at createPanels (splitter.esm.js:373:1)
    at splitter.esm.js:378:1
    at renderWithHooks (react-dom.development.js:16305:1)
    at updateForwardRef (react-dom.development.js:19226:1)
    at beginWork (react-dom.development.js:21636:1)
 ```
splitter-error

 In splitter.esm.js:
```js
  var childrenLength = props.children && props.children.length;

  var panelSize = function panelSize(sizes, index) {
    return index in sizes ? sizes[index] : props.children[index].props.size || 100 / childrenLength;
  };
  ```

childrenLength is undefined, but props.children is this:
props-children

### PR DESCRIPTION
**Pull request by melloware**
### Defect Fixes
Fix #3546: Splitter error with only 1 panel

### CODE REVIEW

**Comment by kalinkrustev** [comment]
Sorry, I did not know children could be non array. But I also wonder if specifying a size for a single panel makes sense, in which case this fix will not apply the size and instead use 100%

**Comment by melloware** [comment]
Sure I was not expecting someone to use 1 panel.  You want to test and submit another PR?

**Comment by kalinkrustev** [comment]
I do not know yet. I will try to check if it makes sense to have one panel width first.

**Comment by kalinkrustev** [comment]
Unfortunately this fix, undid what was fixed by #3535

**Comment by kalinkrustev** [comment]
I think the next fix should also include a snapshot test, so future errors can be limited.

**Comment by melloware** [comment]
I have snapshot tests in place now

**Comment by kalinkrustev** [comment]
Yes, but the snapshots contained incorrect values.
Check here #3646 for the bugfix including support for specifying the size of a single panel and also a few more snapshots.

**Pull request merged**
