### PR TITLE
Multicheckbox component

### PR DESCRIPTION
**Pull request by NathanPB**
I know the project has a disclaimer telling that you guys can accept PRs with major changes, but I took the initiative to develop a new component that would be really useful to me, and I hope that will for a lot of more people that are betting on Prime.

I'm sending this PR implementing a component called "MultiCheckbox", which I described in a feature request made by me here: #1812

It's basically a checkbox that accepts multiple states (similar to TriStateCheckbox, but accepting more than three states) and allow specifying icons for each one of the states.

I made this component using hooks (I know most of PrimeReact is built with class, iif needed I can rewrite with classes). Already made all the documentation and the showcase for that. I'm also reusing styles from the checkbox component.

Thank you very much, I'd appreciate if this PR turns out to be useful for someone else, because it will definitively be for me...

### CODE REVIEW

**Comment by NathanPB** [comment]
@mertsincan :eyes:

**Comment by mertsincan** [comment]
Thanks a lot! I’ll check and get back to you.

**Comment by mertsincan** [comment]
Hi @NathanPB,
First of all, thank you very much for this great effort. I have some feedback on this component.

1. Maybe this component can be named MultiStateCheckbox. TriStateCheckbox vs MultiStateCheckbox ??
2. Can you write as a Class Component in terms of code compatibility? If no, no problem. I can convert this PR to Class Component after merging it.
3. Defining a property named _options_ instead of <Option> tag will make this component more compatible with PrimeReact's other components.

Thanks again!!!!

**Comment by NathanPB** [comment]
> Maybe this component can be named MultiStateCheckbox. TriStateCheckbox vs MultiStateCheckbox ??

Done =)

> Can you write as a Class Component in terms of code compatibility? If no, no problem. I can convert this PR to Class Component after merging it.

I personally dislike this, function components are so much more convenient. But I will do that in a moment

> Defining a property named options instead of tag will make this component more compatible with PrimeReact's other components.

Would we need an API like the MenuModel API to document the ``eligible`` property well?

**Not Related Note:** I'm having problems with the ``node-sass`` package. It's deprecated, and it's a good idea to move to ``sass``

**Comment by NathanPB** [comment]
> Defining a property named options instead of tag will make this component more compatible with PrimeReact's other components

Done!

@mertsincan I had to write a ``useDeepCompareMemoized`` hook to create dependency trees of deep compared objects. Isn't anything that does this already in the project that I'm missing?

I will be moving it to class components sometime in this week

**Comment by mertsincan** [comment]
Thanks a lot for your effort, @NathanPB ;) 

> Not Related Note: I'm having problems with the node-sass package. It's deprecated, and it's a good idea to move to sass
- Done ;) 

> I had to write a useDeepCompareMemoized hook to create dependency trees of deep compared objects. Isn't anything that does this already in the project that I'm missing?
- I'll check it.

Best Regards,

**Pull request merged**
