### PR TITLE
feat: #4919 datatable: reorder+filter - disable drag and drop when filter is applied

### PR DESCRIPTION
**Pull request by thejus557**
feat: #4919 datatable: reorder+filter - disable drag and drop when filter is applied

### CODE REVIEW

**Review by melloware — COMMENTED** [review]
Just thinking out loud I am wonder if it needs to be a property at all? You said it makes no sense to re-order when filtering?

Assigning PrimeTek to review...

**Comment by thejus557** [comment]
Yes it makes no sense. But i have added it as a property to be more specific and clear on things. If it is not required. I can remove the property.

**Comment by melloware** [comment]
@thejus557 i think you can remove the property as this should just be the way it works.

**Comment by mertsincan** [comment]
Hi,

Thanks a lot for your contribution, but it has more conflicts. So, for now, closed.

Also, could you please create a discussion ticket to collect feedback from other users? If we are going to do this, this could be a prop option on DataTable.

**Pull request closed without merging**
