### PR TITLE
Added 'downloadable' prop to Image component

### PR DESCRIPTION
**Pull request by liansnail**
I added 'downloadable' prop to an Image component. This might not be working on some browsers(IE11) because it depends on 'download' attribute of anchor tag.

### CODE REVIEW

**Comment by melloware** [comment]
@loone96 Thansk for the PR!  Can you please create an Issue as well so PrimeTek can link the PR to an Issue for release notes.

**Comment by loone96** [comment]
@melloware Hi! I created issue #2552 . Please let me know if I need something to do.

**Comment by melloware** [comment]
Nope now just sit tight until PrimeTek reviews and hopefully merges it.

**Comment by melloware** [comment]
You need to update 2 more files which are documentation aspects of this new prop...

`\api-generator\components\image.js`

`\components\doc\image\index.js`

**Review by melloware — CHANGES_REQUESTED** [review]
You need to update 2 more files which are documentation aspects of this new prop...

`\api-generator\components\image.js`

`\components\doc\image\index.js`

**Comment by mertsincan** [comment]
Thanks a lot for your contributions!

Best Regards,

**Pull request merged**
