### PR TITLE
Component structure enhancement

### PR DESCRIPTION
**Pull request by gucal**
Component structure enhancement
- Slider
- MultiSelect
- DataTable

### CODE REVIEW

**Review by nitrogenous — CHANGES_REQUESTED** [review]
In the PrimeVue datatable example, row highlighting is not implemented. We should align our behavior in the PrimeReact datatable to match this approach.

https://primevue.org/datatable/#checkbox_row_selection

**Comment by nitrogenous** [comment]
Everything else appears satisfactory, thank you. Waiting for updates but no need to rush

**Comment by melloware** [comment]
Looks like a conflict in MultiSelectPanel.js ?

**Review by melloware — CHANGES_REQUESTED** [review]
LGTM once merge conflict is resolved

**Pull request merged**
