### PR TITLE
Fix #2616: avoid TypeError

### LINKED ISSUE #2616: Automated tests throw "TypeError: highlightItem.scrollIntoView is not a function"
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Codesandbox Case (Bug Reports)**
https://codesandbox.io/s/treeselect-toxz7?file=/src/index.test.js

**Current behavior**
Running tests with jest and @testing-library/react trigger this error for components like Dropdown, MultiSelect, TabView and TreeSelect
This is likely related to jsdom/jsdom#1695 and there is a workaround explained here https://stackoverflow.com/a/53294906/1205028

**Expected behavior**
Error should not be thrown and workarounds should not be needed.

**Minimal reproduction of the problem with instructions**
Open the sandbox link, click the tests, then click the console where the error is shown.

* **PrimeReact version:**
7.2.0

### PR DESCRIPTION
**Pull request by kalinkrustev**
Fixes #2616

### CODE REVIEW

**Comment by kalinkrustev** [comment]
Fixes #2616

**Comment by melloware** [comment]
This seems like a safe check.  Does this happen in real code or only in Jest tests?

**Review by melloware — APPROVED** [review]

**Comment by kalinkrustev** [comment]
It is likely to happen only in tests, but may also happen in other cases which use jsdom. Maybe SSR.

**Comment by mertsincan** [comment]
Hi @kalinkrustev,

Thanks a lot for your contribution!

Best Regards,

**Pull request merged**
