### PR TITLE
fix InputText reset value issue

### PR DESCRIPTION
**Pull request by christinJiang**
###Defect Fixes
image

PrimeReact DataTable Column filters work right after user input name "tomy".
While user presses 'reset' button to clear all column filters, the datatable clear all column filters, the table will show all rows without filters. But the column filter InputText element still show the string 'tomy'.

###Feature Requests
    const columnElements = visibleColumns.map(col => (
      <Column
        key={col.field}
        field={col.field}
        header={col.header}
        style={{ width: `${col.width}px`, minWidth: '50px' }}
        filter={col.filterable === 'true'}
        filterElement={
          <InputText
            type="search"
            value={filters[col.field]}
            onInput={e => this.colFilter(e, col.field)}
          />
        }
        body={this.bodyTemplate}
        sortable
      />
    ));

  colFilter = (e, tag) => {
    const { dispatch, filters } = this.props;
    filters[tag] = e.target.value;
    dispatch({
      type: 'xxx/updateFilters',
      payload: {
        filters,
      },
    });
  };

### CODE REVIEW

**Comment by christinJiang** [comment]
resetTable(state) {
      return {
        ...state,
        // clear column filters
        filters: {},
      };

**Comment by christinJiang** [comment]
I am working in GE company, my project uses primereact and met this issue. Could you help to merge my pull request? I will upgrade my primereact version after the code is merged by you.

**Comment by christinJiang** [comment]
Hi @mertsincan @cagataycivici @Merve7 @onursenture,

This pull request is important to my project, could you please help to merge the pull request.

**Comment by mertsincan** [comment]
Sorry for the delayed response. I'll check and get back to you.

Thanks a lot for the PR and contribution.

**Comment by mertsincan** [comment]
I think you need to add this condition to your code. 
The inputText element is under your control in filterElement. Therefore, this is not related to the core.  Also, could you please try it with html input element? 

Maybe, you can do;
```
<InputText
type="search"
value={filters[col.field] || ''}
```

Best Regards,

**Pull request closed without merging**
