### PR TITLE
Core: Merging PT props only respects lower-case props

### PR DESCRIPTION
**Pull request by vaelu**
Fixes https://github.com/primefaces/primereact/issues/6289.

### CODE REVIEW

**Comment by vaelu** [comment]
@melloware In the sidebar preset there is a closeButton, but in the definition, no closeButton exists.
https://github.com/primefaces/primereact/blob/master/components/lib/passthrough/tailwind/index.js#L435-L443

**Comment by vaelu** [comment]
`checkbox` is missing from `TriStateCheckbox` component: https://github.com/primefaces/primereact/blob/master/components/lib/passthrough/tailwind/index.js#L1032-L1045

**Comment by vaelu** [comment]
`header` is missing from `Editor` component definition: https://github.com/primefaces/primereact/blob/master/components/lib/passthrough/tailwind/index.js#L1597-L1599

**Comment by vaelu** [comment]
`content` is missing from `ContextMenu` component definition: https://github.com/primefaces/primereact/blob/master/components/lib/passthrough/tailwind/index.js#L1781-L1792

**Comment by vaelu** [comment]
`content` is missing from `Menu` component definition: https://github.com/primefaces/primereact/blob/master/components/lib/passthrough/tailwind/index.js#L1849-L1857

**Comment by vaelu** [comment]
`submenu` is missing from `Menubar` component definition: https://github.com/primefaces/primereact/blob/master/components/lib/passthrough/tailwind/index.js#L1916-L1920

**Comment by vaelu** [comment]
`menuButton` is missing from `MegaMenu` component definition: https://github.com/primefaces/primereact/blob/master/components/lib/passthrough/tailwind/index.js#L1966-L1972

`submenuItem` is missing from `MegaMenu` component definition: https://github.com/primefaces/primereact/blob/master/components/lib/passthrough/tailwind/index.js#L1982-L1984

`grid`, `column`, `submenu` and `submenuHeader` are missing from `MegaMenu` component definition: https://github.com/primefaces/primereact/blob/master/components/lib/passthrough/tailwind/index.js#L1996-L2003

**Comment by vaelu** [comment]
`submenu` is missing from `PanelMenu` component definition: https://github.com/primefaces/primereact/blob/master/components/lib/passthrough/tailwind/index.js#L2048-L2050

**Comment by vaelu** [comment]
`submenu` is missing from `SlideMenu` component definition: https://github.com/primefaces/primereact/blob/master/components/lib/passthrough/tailwind/index.js#L2125-L2127

**Comment by vaelu** [comment]
`content` is missing from `TieredMenu` component definition: https://github.com/primefaces/primereact/blob/master/components/lib/passthrough/tailwind/index.js#L2138-L2149

**Comment by vaelu** [comment]
@melloware @nitrogenous Is a `class` array deliberately used here instead of an object with `className`? https://github.com/primefaces/primereact/blob/master/components/lib/passthrough/tailwind/index.js#L2164-L2260

**Comment by vaelu** [comment]
`indicatorbutton` is missing from `Galleria` component definition: https://github.com/primefaces/primereact/blob/master/components/lib/passthrough/tailwind/index.js#L2367-L2372

**Comment by vaelu** [comment]
`wrapper` is missing from `Tree` component definition: https://github.com/primefaces/primereact/blob/master/components/lib/passthrough/tailwind/index.js#L2460

**Comment by vaelu** [comment]
`grid` is missing from `DataScroller` component definition: https://github.com/primefaces/primereact/blob/master/components/lib/passthrough/tailwind/index.js#L2613

**Comment by vaelu** [comment]
`targetcontrols`, `targetwrapper`, `targetheader`, `targetlist` and `transition` are missing from `PickList` component definition: https://github.com/primefaces/primereact/blob/master/components/lib/passthrough/tailwind/index.js#L2874-L2888

**Comment by vaelu** [comment]
`jumptopagedropdown` (or like the other namings are `JTPDropdown`) is missing from `Paginator` component definition: https://github.com/primefaces/primereact/blob/master/components/lib/passthrough/tailwind/index.js#L3027-L3041

**Comment by vaelu** [comment]
`footercell`, `checkboxwrapper`, `checkbox`, `checkboxIcon`, `rowreordericon`, `radiobuttonwrapper`, `radiobutton`, `radiobuttonicon`, `headercheckboxwrapper` and `headercheckboxicon` are missing from `Column` component definition: https://github.com/primefaces/primereact/blob/master/components/lib/passthrough/tailwind/index.js#L3205-L3225

**Comment by vaelu** [comment]
`rowgrouptoggler` and `rowgrouptogglericon` are missing from `DataTable` component definition: https://github.com/primefaces/primereact/blob/master/components/lib/passthrough/tailwind/index.js#L3502-L3511

**Review by melloware — APPROVED** [review]

**Comment by vaelu** [comment]
@melloware Ready to merge.

**Pull request merged**
