### PR TITLE
Fix #6095 'dialog focus display none'  

### LINKED ISSUE #6095: Dialog: (accessibility) "display: none" inside dialog breaks focus tabbing
### Describe the bug

When a Dialog contains a section with "display: none" and a <input/> as child of section, user cannot reach each focusable input/buttons/... using TAB key.

### Reproducer

https://stackblitz.com/edit/qejj7w?file=src%2FApp.jsx

### PrimeReact version

10.5.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

_No response_

### Steps to reproduce the behavior

1. open stackBlitz app  (spawn from Dialog basic showcase)
2. use tab to move set focus on all input & buttons:  (this works)
3. open dialog
4. use tab to move focus around dialog's buttons and inputs:  Focus is stopped on input due to "display: none" section.

50 cents: Issue comes from DomHandler.getFocusableElements() ?

Note that issue is not the same as  https://github.com/primefaces/primereact/issues/4035

### Expected behavior

All focusable elements inside a dialog box should be reached using Tab (Shift+Tab) key.

### PR DESCRIPTION
**Pull request by KirilCycle**
### Defect Fixes
Fix #6095
## Focus Loop

PR implements a loop that iterates through an array of focusable elements. It keeps trying to focus on the next element until:

* **Focus successful:** The loop successfully focuses on an element.
* **Array ends:** There are no more elements in the array.

## Note 
Works fine with deep nested focusable elements in display none parent
Without 'onKeyDown' method tab pressing functions well

## Video description: 

https://github.com/primefaces/primereact/assets/118115736/fbac77b8-1edc-4cae-90d7-edd6364a5215

### CODE REVIEW

**Comment by melloware** [comment]
@KirilCycle i think I know what is going on here let me do some testing!

**Comment by KirilCycle** [comment]
I found easier solution

**Comment by KirilCycle** [comment]
> @KirilCycle i think I know what is going on here let me do some testing!

I found a new easier solution

**Comment by melloware** [comment]
@KirilCycle see my PR.  I fixed it how PrimeVue is doing it using the `FocusTrap` component.

https://github.com/primefaces/primereact/pull/6435

**Comment by melloware** [comment]
I am going to close this one in favor of my FocusTrap fix PR.

**Pull request closed without merging**
