### PR TITLE
fix(input-number): when zero is entered, value displayed isn't expected

### LINKED ISSUE #5234: InputNumber: Enter leading 0 when using prefix/suffix
### Describe the bug

Reported at PrimeVue: https://github.com/primefaces/primevue/issues/4539

Same bug exists in PrimeReact

### Reproducer

_No response_

### PrimeReact version

10.0.9

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

_No response_

### Steps to reproduce the behavior

1. Go to https://primereact.org/inputnumber/#prefixsuffix
2. Find the input field labeled as Expiry
3. Delete the content of the input and type 012345
4. See the input now has value 345 instead of what you typed

### Expected behavior

_No response_

### PR DESCRIPTION
**Pull request by betavs**
From https://github.com/primefaces/primevue/issues/4539

Fix #5234

### CODE REVIEW

**Comment by betavs** [comment]
If this solution works, I'll optimize the code again.

**Comment by melloware** [comment]
@betavs so the only real change is this line?

```js
inputEl.setSelectionRange(selectionEnd + 1, selectionEnd + 1);
```

to

```js
inputEl.setSelectionRange(selectionEnd, selectionEnd);
```

???

**Comment by betavs** [comment]
> @betavs so the only real change is this line?
> 
> ```js
> inputEl.setSelectionRange(selectionEnd + 1, selectionEnd + 1);
> ```
> 
> to
> 
> ```js
> inputEl.setSelectionRange(selectionEnd, selectionEnd);
> ```
> 
> ???

Yes, but I think it can be optimized to

```typescript
if (['insert', 'delete-back-single', 'delete-range', 'spin'].includes(operation)) {
    inputEl.setSelectionRange(selectionEnd, selectionEnd);
} else if (operation === 'delete-single') {
    inputEl.setSelectionRange(selectionEnd - 1, selectionEnd - 1);
}
```

**Comment by melloware** [comment]
OK can you update your PR for your optimization so I can test it.

**Review by melloware — APPROVED** [review]
Tested and looking good to me.

**Pull request merged**
