### PR TITLE
refactor (docs): Datatable example in ts compile without warnings

### LINKED ISSUE #2490: Showcase: Update all TypeScript samples
**I'm submitting a ...** 
```
[x] bug report
```

**Codesandbox Case (Bug Reports)**

updated code sample: https://codesandbox.io/s/cranky-wind-6v50x
Existing code sample: https://codesandbox.io/s/ykcro

**Current behavior**
Works but has warnings/errors.
Running the demo code from here https://primefaces.org/primereact/showcase/#/datatable/filter (TS) in codesandbox.

**Expected behavior**
Demo works without errors.

Launch the existing documented demo in codesandbox, note errors and warnigns.

codesandbox.

* **React version:**
17.01

* **PrimeReact version:**
7.1

* **Browser:** 
Chrome.
 
* **Language:** 
Typescript

### PR DESCRIPTION
**Pull request by jafin**
Fixes #2490
When the example is brought into codesandbox.io it will run but shows errors and warnings.
This PR is to resolve those errors so the sample code shows no errors/warnings on execution.

* add stronger types

### CODE REVIEW

**Comment by melloware** [comment]
See https://github.com/primefaces/primereact/pull/2488 I am converting those FilterMatchMode options to proper TypeScript enums

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
Can you resolve the conflicts of your branch now that my fix has been merged?

**Comment by jafin** [comment]
@melloware done.

**Comment by melloware** [comment]
Nice work!

**Comment by mertsincan** [comment]
Thanks a lot! We'll update all TS samples in showcase. For now, closed.

Thanks again!
Best Regards,

**Pull request closed without merging**
