### PR TITLE
Port fixes that were lost

### LINKED ISSUE #4051: ConfirmDialog/ConfirmPopup: Add `defaultFocus` option like PrimeVue
### Describe the feature you would like to see added

The basic `confirmDialog` is a perfect solution for getting the user's confirmation before execution. However, in some cases I would like to not have the accept button highlighted for example on a delete confirmation. For a delete I would like to have the reject selected as default to avoid accidential consequences of keyboard button pressing.

### Is your feature request related to a problem?

Right now I can swap the accept and reject buttons but it's logically not right and the places also swap. Another way is to create my own footer but this way the component lose its ease of use and I mostly need to copy the original implementation and set the `autoFocus` on the other button.

### Describe the solution you'd like

It would be great if we could have a `focusReject` boolean prop for Confirm Dialog which is `false` by default. If the user sets it to `true` the reject button would be auto focused instead of the accept one.

I would change this part:

https://github.com/primefaces/primereact/blob/5edbb9f4e607a9d240d07382457928db4023c484/components/lib/confirmdialog/ConfirmDialog.js#L115-L116

to something like that:
```js
<Button label={rejectLabel} icon={getPropValue('rejectIcon')} className={rejectClassName} onClick={reject} autoFocus={focusReject} />
<Button label={acceptLabel} icon={getPropValue('acceptIcon')} className={acceptClassName} onClick={accept} autoFocus={!focusReject} />
```

### Describe alternatives you have considered

_No response_

### Additional context

The same could be done for `confirmPopup`.

### LINKED ISSUE #5370: TreeTable: selected rows are not highlighted
### Describe the bug

For components homogeneities,  the rows selected using checkbox selection should be highlighted like DataTable component.

### Reproducer

https://codesandbox.io/p/sandbox/primereact-demo-2fyn7s?file=%2Fsrc%2Findex.js

### PrimeReact version

10.0.9

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

_No response_

### Steps to reproduce the behavior

_No response_

### Expected behavior

_No response_

### LINKED ISSUE #5457: TabMenu: activeIndex not rerendering tabs with Tailwind
### Describe the bug

TabMenu does not change the new tab when activeIndex is changed.

### Reproducer

https://codesandbox.io/p/sandbox/floral-dew-h9kdfq

### PrimeReact version

10.2.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome, Safari

### Steps to reproduce the behavior

1. Click on a new tab

### Expected behavior

New tab is highlighted.

### LINKED ISSUE #5487: TreeTable: Header's columns not aligned with body's columns in scrollable mode
### Describe the bug

In scrollable mode, the header (containing the columns titles) and the body are in 2 separated tables, so the header's columns are not always aligned with the body's columns.
scrollable-treetable

### Reproducer

https://codesandbox.io/p/sandbox/primereact-demo-forked-xwsn9c

### PrimeReact version

10.1.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Chrome 119

### Steps to reproduce the behavior

In the table of the reproducer, scroll on the right side and watch the shift between the titles and the body.

### Expected behavior

TreeTable in scrollable mode should have the same structure than in no-scrollable mode, with the titles and body cells in the same table

### LINKED ISSUE #5556: DataTable: Error when updating a cell
### Describe the bug

I've got the below console error when updating a cell

image

**Minimal code reproduction**:

```js
export default function PrimeDataTable() {
  const [data, setData] = React.useState([
    {
      value: '2',
    },
  ]);
  return (
    <DataTable value={data}>
      <Column
        field="value"
        editor={options => (
          <input
            value={options.value}
            onChange={event => options.editorCallback?.(event.target.value)}
          />
        )}
        onCellEditComplete={({ newValue }) => {
          setData([{ value: newValue }]);
        }}
      />
    </DataTable>
  );
}
```

### Reproducer

https://codesandbox.io/p/sandbox/primereact-demo-forked-v94dr7?file=%2Fsrc%2FApp.js

### PrimeReact version

10.1.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

_No response_

### Steps to reproduce the behavior

1. Use a DataTable with cell edit mode
2. Update a React state inside the onCellEditComplete

### Expected behavior

The error `Cannot update a component` should not be displayed in the console.

### LINKED ISSUE #5640: DataTable: disable the `rowEditor` prop dynamically, as is done in `rowExpansion`
### Discussed in https://github.com/orgs/primefaces/discussions/756

<div type='discussions-op-text'>

<sup>Originally posted by **datacampsis** December 22, 2023</sup>
In rowExpansion, we can disable the prop `expander` if data has a specific value.
Example:
`const allowExpansion = (rowData: Product) => {
        return rowData.orders!.length > 0;
    };`
    
 In the `rowEditor`, there is no such option.
 
 Add the option to disable this prop with a specific condition. Like this:
 
 `const allowEditor = (rowData: Product) => {
        return rowData.orders!.length > 0;
    };`
    
    <Column 
         rowEditor={allowEditor}
    />
    
    </div>

### PR DESCRIPTION
**Pull request by melloware**
Fix #5640
Fix #5556
Fix #5487
Fix #5457
Fix #5370
Fix #4051

### CODE REVIEW

**Comment by melloware** [comment]
cc @kl-nevermore

**Comment by kl-nevermore** [comment]
@melloware 
Do I resubmit all fixes to a PR or wait for PrimeTek to process it?

**Comment by melloware** [comment]
I would resubmit anything you see missing.

**Comment by melloware** [comment]
I ported the ones that people reported as missing but I am sure there are more

**Comment by kl-nevermore** [comment]
Okay, I'll check in the morning and put the missing PR comment here.

**Comment by kl-nevermore** [comment]
## Page 6
- [ ] #5359
- [ ] #5361
- [ ] #5364
- [ ] #5366
- [ ] #5368
- [ ] #5373
- [ ] #5375
- [ ] #5381
- [ ] #5386
- [ ] #5391 
- [ ] #5392
- [ ] #5394
- [ ] #5397
- [ ] #5402
- [ ] #5403
- [ ] #5405

**Comment by kl-nevermore** [comment]
## Page 5

- [ ] #5431
- [ ] #5416
- [ ] #5418
- [ ] #5419
- [ ] #5430
- [ ] #5431
- [ ] #5433 
- [ ] #5434 
- [ ] #5436 
- [ ] #5441 
- [ ] #5448 
- [ ] #5449
- [ ] #5451
- [ ] #5454
- [ ] #5470
- [ ] #5473
- [ ] #5474
- [ ] #5475

**Comment by kl-nevermore** [comment]
## Page 4
- [ ] #5482
- [ ] #5483
- [ ] #5484
- [ ] #5486
- [ ] #5491
- [ ] #5503 
- [ ] #5504
- [ ] #5505 
- [ ] #5506
- [ ] #5507 
- [ ] #5510 
- [ ] #5516
- [ ] #5519 
- [ ] #5520

**Comment by kl-nevermore** [comment]
## Page 3
- [ ] #5525 
- [ ] #5527 
- [ ] #5531 
- [ ] #5532 
- [ ] #5538 
- [ ] #5539 
- [ ] #5544 
- [ ] #5547 
- [ ] #5549 
- [ ] #5552 
- [ ] #5554 
- [ ] #5557 
- [ ] #5559 
- [ ] #5562 
- [ ] #5565 
- [ ] #5571 
- [ ] #5573 
- [ ] #5576 
- [ ] #5578 
- [ ] #5579

**Comment by kl-nevermore** [comment]
## Page 2
- [ ] #5585 
- [ ] #5586 
- [ ] #5592 `and` #5601
- [ ] #5595 
- [ ] #5598 
- [ ] #5602 
- [ ] #5608 
- [ ] #5612 
- [ ] #5614 
- [ ] #5615 
- [ ] #5624 
- [ ] #5625 
- [ ] #5628 
- [ ] #5634
- [ ] #5638 
- [ ] #5641 
- [ ] #5646 
- [ ] #5647 
- [ ] #5649

**Comment by kl-nevermore** [comment]
## Page 1
- [ ] #5654

**Pull request merged**
