### PR TITLE
#4589: Fix adding icon to chips

### LINKED ISSUE #4589: Chips: Adding icons to chips creates overlapping text into the icon
### Describe the bug

image

So with input text if you add an icon it works as expected but for Chips the input text and the chip start overlapping into the icon. I tried adding a padding or margins to the Chips className but it will behave weirder. 

This might be just css but I haven't investigated yet. But this has been in my backlog to post.

https://codesandbox.io/s/primereact-demo-forked-l8qhcf?file=/src/App.js

### Reproducer

_No response_

### PrimeReact version

9.6.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Next.js

### Browser(s)

_No response_

### Steps to reproduce the behavior

_No response_

### Expected behavior

_No response_

### PR DESCRIPTION
**Pull request by bu3alwa**
image

This is not the way primereact does it for inputtext. I see it done on a per theme basis and I am not sure why. But this is my fix and implementation for it with the docs being updated.

Fix #4589

### CODE REVIEW

**Comment by melloware** [comment]
It easy to add the CSS to to themes now just update the SCSS here: https://github.com/primefaces/primereact-sass-theme

Just open an issue ticket there and link it to your main issue ticket here!

**Comment by bu3alwa** [comment]
> It easy to add the CSS to to themes now just update the SCSS here: https://github.com/primefaces/primereact-sass-theme
> 
> Just open an issue ticket there and link it to your main issue ticket here!

Oh okay I see. Ill take a look tomorrow and create an issue and a fix. Ill update this PR as well.

**Comment by bu3alwa** [comment]
Why is this complaining about the issue not being linked?

**Comment by melloware** [comment]
Put the word "Fix" in front of it like "Fix #xxx"

**Comment by bu3alwa** [comment]
Still failing on verify linked issue in PR

**Comment by melloware** [comment]
Weird because she. I look at the ticket it's linked.

**Comment by melloware** [comment]
Do you need to remove the CSS from this PR now that you moved it to the SASS Theme?

**Comment by bu3alwa** [comment]
I moved the parts that were are supposed to be in the sass. The rest should be here and its similar to how inputtext css looks like.

**Comment by bu3alwa** [comment]
Will you merge this or do the others have to be merged first?

**Comment by melloware** [comment]
Because there are theme.css changes I usually wait until PrimeTek approves and merges those first before merging the code changes associated to them.

**Comment by melloware** [comment]
@bu3alwa can you resolve your merge conflicts?

**Comment by bu3alwa** [comment]
I'll look into it tonight

**Comment by bu3alwa** [comment]
It seems that all the scss files were deleted from the library. So not sure where primereact is headed or where the css should be now.

**Comment by melloware** [comment]
Look in ChipsBase.JS they are moving to Css in JS to support unstyled mode.

**Review by melloware — APPROVED** [review]

**Pull request merged**
