### PR TITLE
Fix #3107: ImperativeHandle put props first

### LINKED ISSUE #3107: Tree: Custom filter broken due to overwritten props in useImperativeHandle hook.
### Describe the bug

The `filter` prop of Tree component overwrites the `filter` function in the `useImperativeHandle` hook, breaking the custom filtering function.
In https://github.com/primefaces/primereact/blob/master/components/lib/tree/Tree.js, line 297

```
    React.useImperativeHandle(ref, () => ({
        filter,
        getElement: () => elementRef.current,
        ...props
    }));
```

### Reproducer

https://codesandbox.io/embed/primereact-test-forked-dggjdr?fontsize=14&hidenavigation=1&theme=dark

### PrimeReact version

8.3.0

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Browser(s)

_No response_

### Steps to reproduce the behavior

_No response_

### Expected behavior

_No response_

### PR DESCRIPTION
**Pull request by melloware**
###Defect Fixes
Fix #3107: ImperativeHandle put props first

So the properties don't clobber methods like `filter`

### CODE REVIEW

**Comment by mertsincan** [comment]
Maybe, it can be like;
```
this.dtRef.current.props.first  instead of this.dtRef.current.first

Exp;
const datatableInstance = this.dfRef.current;

datatableInstance.props
datatableInstance.resetFilter
...
```
WDYT?

**Comment by melloware** [comment]
@mertsincan that is what I wanted to do but it wouldn't let me do this...

```js
    React.useImperativeHandle(ref, () => ({
        props: ...props,
        getElement: () => elementRef.current
    }));
```

The only thing i could see doing was ...

```js
    React.useImperativeHandle(ref, () => ({
        getProps: () =>  ...props,
        getElement: () => elementRef.current
    }));
```

But not sure I liked that either.  Any help here would be appreciated!

**Comment by mertsincan** [comment]
Could you please try;
```
React.useImperativeHandle(ref, () => ({
        props,
        getElement: () => elementRef.current
}));
```
What error do you get when you use it?

**Comment by melloware** [comment]
Let me try...

**Comment by melloware** [comment]
DUH!  that works great and is exactly what we want.  I just updated the PR.

**Pull request merged**
