### PR TITLE
Stepper: add header position

### PR DESCRIPTION
**Pull request by TikouWeb**
#7025
New feature for stepper: customise header position

### CODE REVIEW

**Comment by nitrogenous** [comment]
Thanks for the PR. We're trying to keep our library structures synced, so we'll check this core update and get back to you

**Comment by TikouWeb** [comment]
@nitrogenous Noted, Thanks for reviewing it

**Review by nitrogenous — APPROVED** [review]
LGTMGTM

**Comment by nitrogenous** [comment]
Your PR looks great! Thank you for your contribution. We would love to see more PRs from you in the future @TikouWeb

**Comment by TikouWeb** [comment]
Nice to see a LGTM for my first open source contribution ever 😀. 
Thank you! I'm glad the PR was helpful. I’d be happy to contribute more in the future ✌️

**Comment by melloware** [comment]
@TikouWeb yes excellent job!

**Pull request merged**
