### PR TITLE
Fixed #3039 | FilterTemplate support for components

### LINKED ISSUE #3039: FilterTemplate support for components
### Describe the feature you would like to see added

- Dropdown
- OrderList
- ListBox
- MultiSelect
- TreeSelect
- Tree

### Is your feature request related to a problem?

_No response_

### Describe the solution you'd like

_No response_

### Describe alternatives you have considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by cetincakiroglu**
Add filterTemplate support for components.

- MultiSelect
- ListBox
- OrderList (filter + filterTemplate)
- Dropdown
- Tree
- TreeSelect

### CODE REVIEW

**Comment by iantrudell** [comment]
Docs need updating to show an example of filterTemplate usage

**Comment by melloware** [comment]
@iantrudell a great way to get involved would be to submit a P4 updating the docs

**Comment by muffinfaery** [comment]
> @iantrudell a great way to get involved would be to submit a PR updating the docs

Adding a feature to the library without documentation is not the correct behavior form a development team this is not the consumers responsibility in any capacity. This PR should have been denied without the documentation end of story

**Comment by muffinfaery** [comment]
> @muffinfaery you do know what Open Source is right? It means anyone can contribute and a great way for new people to get involved is to provide Documentation updates and PR's. So I am not sure what your point is?
> 
> And the PR was from a PrimeTek employee so who was going to deny it?

I'm glad you are encouraging helping and to build up folks involvement in the community. I simply find it strange that you suggest that an open source library with the backing of a member organization that reviews and merges commits as a team (even charges for some things, as they should) should not be responsible for its own quality. 

Fundamentally it sounds like you and I have different expectations when it comes to release ready features. I find the lack of documentation and constant requests for examples of features in the Primetek git issues to be a compelling reason for those to be wary of this library to solve their concerns when involving less capable or untrained developers.

**Comment by melloware** [comment]
Understood, I get your points.

But a few things to remember....

- It is open source.  
- If you see something you don't like fix it by submitting a PR and being a member of a community.
- "less capable or untrained developers" seems like a governance and training issue in your organization and not a concern of this community right?

**Pull request merged**
