### PR TITLE
Fix #6503: remove unused codes

### LINKED ISSUE #6503: Accordion: Unused code remove
### Describe the bug

There are unused codes at accordion component.

ss1

### Reproducer

_No response_

### PrimeReact version

10.6.3

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Browser(s)

_No response_

### Steps to reproduce the behavior

_No response_

### Expected behavior

_No response_

### PR DESCRIPTION
**Pull request by Rekl0w**
Fix #6503: remove unused codes

### CODE REVIEW

**Comment by melloware** [comment]
Run `npm run format`

**Comment by Rekl0w** [comment]
I runned it nothing changed.

**Comment by Rekl0w** [comment]
ss2

**Comment by melloware** [comment]
Ahh it looks like a class you didn't touch...

**Pull request merged**
