### PR TITLE
Fix #6456 : Toast close by id fix

### LINKED ISSUE #6456: Toast always closes all messages
### Describe the bug

Closing one of several messages closes all messages. Independent of their sticky-value. This is a breaking behaviour opposit to PrimeReact 9.6.5. This behaviour can be reproduced in both official demo-applications of PrimeReact (10.6.3 vs. 9.6.5)
Closing a single message and leave all other messages open is important.
How to deal with it in 10.6.3?
Thx guys!

### Reproducer

_No response_

### PrimeReact version

10.6.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

Google Chrome Version 122.0.6261.129 (Offizieller Build) (64-Bit)

### Steps to reproduce the behavior

Please compare behaviour in both demo of Primereact (10.6.3 vs. 9.6.5)

### Expected behavior

Every toast should be closed on its own

### PR DESCRIPTION
**Pull request by Rekl0w**
Fix #6456 : Toast close by id fix

### CODE REVIEW

**Review by melloware — CHANGES_REQUESTED** [review]
Please retest the following tickets: 

https://github.com/primefaces/primereact/issues/5972

https://github.com/primefaces/primereact/issues/5083

Your change will cause both of these tickets to regress.

**Comment by Rekl0w** [comment]
I tried all of this. This works good. @melloware

**Comment by melloware** [comment]
Can you also check `Messages.js` it has similar code.

**Comment by Rekl0w** [comment]
I saw that, i can fix it too if need.

**Comment by melloware** [comment]
Yep may as well make the same fix in this PR.  I usually fix Toast and Messages together as they are similar.

**Comment by Rekl0w** [comment]
Done

**Pull request merged**
