### PR TITLE
Fix: Editor: onTextChange handler does not reflect updated props

### LINKED ISSUE #6067: Editor: onTextChange handler does not reflect updated props
### Describe the bug

The onTextChange handler of the PrimeReact Editor component appears to be caching the initial value of props passed to its containing component, leading to inconsistencies in behavior when those props change.

### Reproducer

https://stackblitz.com/edit/ylsaqj?file=src%2FApp.jsx

### PrimeReact version

10.5.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

_No response_

### Steps to reproduce the behavior

1) Attempt to access a prop value inside onTextChange handler of `<Editor />`.

from the stackblitz example:

1) click on the add button a couple of times, to update the count.
2) type in both the textarea and in the Editor.
3) check the console: onChange can access the current value. OnTextChange reports the initial value.

### Expected behavior

You should be able to access the current prop values. Instead, props return their initial value.

### PR DESCRIPTION
**Pull request by kl-nevermore**
Fix #6067

### CODE REVIEW

**Comment by melloware** [comment]
Hmmm I like simple but i also like how powerful that useEvent hook is an could be useful in the future?

**Comment by kl-nevermore** [comment]
https://github.com/reactjs/react.dev/pull/5373
Yes, it is needed many times, but there have been some changes and it has not been updated in a long time.

**Comment by kl-nevermore** [comment]
use simple writing seems to be no problem, but `onTextChange` will not be executed under jest.

**Comment by melloware** [comment]
OK then lets go with the simplest changes?

**Comment by kl-nevermore** [comment]
resubmitted a PR and fixed test case

**Pull request closed without merging**
