### PR TITLE
Fixing accessibility issue of dropdown

### PR DESCRIPTION
**Pull request by ImmortalRabbit**
### Defect Fixes

Fixes: #6030 

PR fixes accessibility issue of dropdown: Accessibility users were able to navigate through dropdown but screen reader won't read labels of dropdown options making component unusable. 

It was happening because dropdown options were not focusable, and focused element were not actually attempting to focus on targeted element. So, by focusing them using manually upon triggering onFocus element function fixed the problem.

Additionally, introduced additional accessibility attributes that would improve explanation of dropdown options 
`aria-setsize`, `aria-posinset`. Inspiration came from primeng/dropdown component.

### CODE REVIEW

**Comment by melloware** [comment]
@ImmortalRabbit can you run `npm run format` it will fix the formatting.

**Comment by ImmortalRabbit** [comment]
> @ImmortalRabbit can you run `npm run format` it will fix the formatting.

Done!

**Comment by melloware** [comment]
@ImmortalRabbit i just cc'ed you on another ticket.  Its NDVA dropdown related.

**Comment by ImmortalRabbit** [comment]
> @ImmortalRabbit i just cc'ed you on another ticket. Its NDVA dropdown related.

When I could expect to see the new version to be released?

**Comment by melloware** [comment]
That is up to PrimeTek they control the releases.

**Comment by donSan4o** [comment]
fix with focusOnItem function broke this https://primereact.org/dropdown/#filter keyboard control - Lost focus on search input

**Pull request merged**
