### PR TITLE
fix: show viewDate year when yearNavigator mode

### LINKED ISSUE #7234: Calendar: The yearNavigator does not update the displayed year after selecting a new year.
### Describe the bug

If you select a month, the month name is correctly displayed in the dropdown. However, if you select a year, the year does not update in the dropdown.

I replicated this issue using your Stackblitz environment with the following code:

      <Calendar
        value={date}
        onChange={(e) => setDate(e.value)}
        showButtonBar
        monthNavigator={true}
        yearNavigator={true}
      />
   

### Reproducer

https://stackblitz.com/edit/zhfzqk?file=src%2FApp.jsx

### System Information

```Shell
npmPackages:
    primereact: 10.8.2 => 10.8.2 
    react: 18.2.0 => 18.2.0 
  Binaries:
    Node: 20.16.0 - /usr/local/bin/node
    npm: 10.8.1 - /usr/local/bin/npm
```

### Steps to reproduce the behavior

Set yearNavigator={true} in the Calendar component, then try to change the year using the dropdown. The selected year is not updated in the dropdown

### Expected behavior

The selected year should be displayed correctly in the dropdown

### PR DESCRIPTION
**Pull request by KumJungMin**
## Defect Fixes
- fix: #7234

### how to resolve
- When using `yearNavigator` mode, changing the year in the select input doesn't update the displayed year. 
- This happens because the select input is showing the `currentYear` instead of the year selected by the user.
- Therefore, I changed it to display `viewYear` instead of `currentYear` to ensure that the select input reflects the year selected by the user.
```js
// before
const createTitleYearElement = (metaYear) => {
    const viewDate = getViewDate();
    const viewYear = viewDate.getFullYear();
    const displayYear = props.numberOfMonths > 1 ? metaYear : currentYear; // here!
    ...
```
```js
// after
const createTitleYearElement = (metaYear) => {
    const viewDate = getViewDate();
    const viewYear = viewDate.getFullYear();
    const displayYear = props.numberOfMonths > 1 ? metaYear : viewYear; // here!
    ...
```

### test

- First, I verified that the issue has been resolved.

https://github.com/user-attachments/assets/ed6514e9-8f49-4e27-b441-2fbaf5aac995

<br/>

> related issue: Incorrect year with numberOfMonths and yearNavigator
- Second, I have confirmed that related issue no longer occurs after the code modification. 
([related PR link](https://github.com/primefaces/primereact/pull/6294/files), [related issue link](https://github.com/primefaces/primereact/issues/6285))

https://github.com/user-attachments/assets/a2a2a3a8-997e-4d70-a089-35c3d158da12

### CODE REVIEW

**Comment by melloware** [comment]
@KumJungMin can you test this scenario: https://github.com/primefaces/primereact/issues/6285  That is why it was using `currentYear` so I think we need to make it smart based on single mode or multiple month mode?

**Review by melloware — CHANGES_REQUESTED** [review]
See comment

**Comment by KumJungMin** [comment]
@melloware oh! I tested for the issues you mentioned
I was writing test information in a draft PR document.
Could you please check again? :)

**Comment by melloware** [comment]
OK awesome!

**Review by melloware — APPROVED** [review]

**Comment by blan19** [comment]
@melloware @KumJungMin 
PR is already merged, but noticed that there might be an additional scenario that requires a consideration.

#### In the original code:
```typescript
const displayYear = props.numberOfMonths > 1 ? metaYear : currentYear;
```

https://github.com/user-attachments/assets/14f539a3-9e7a-45b5-8d94-67284a509ab8



#### In the merged code:
```typescript
const displayYear = props.numberOfMonths > 1 ? metaYear : viewYear;
```

https://github.com/user-attachments/assets/17bb019e-fd83-4c76-a3de-47b834f2c4e1

when selects a year in the calendar component's year view, it seems that this selection is not being reflected when transitioning to the month view.

thank you for your time and consideration xD

**Pull request merged**
