### PR TITLE
fix: #5349, PanelMenu: Menu items with no sub-items toggling border

### PR DESCRIPTION
**Pull request by akshayaqburst**
### Defect Fixes
fix: #5349, PanelMenu: Menu items with no sub-items toggling border

### CODE REVIEW

**Comment by melloware** [comment]
I think it should be handled like this: https://github.com/primefaces/primevue/pull/4844

The toggler should not even be shown:

image

**Review by melloware — CHANGES_REQUESTED** [review]
See comments

**Comment by dy-xiaodong2022** [comment]
> I think it should be handled like this: [primefaces/primevue#4844](https://github.com/primefaces/primevue/pull/4844)
> 
> The toggler should not even be shown:
> 
> image

Hi, thanks for your reference but I don’t think that remove the empty space or remove the icon is a good idea.
I think it should always show the sub-items menu and the icon if there is a items prop given, even it is empty,
Sometimes user may want to show an empty list.
If they don’t want the list, they should not add the items props.
Another way, maybe adding a tip text on the empty place is the best way to solve this problem.
So this pr should be **closed**.

**Comment by dy-xiaodong2022** [comment]
> > I think it should be handled like this: [primefaces/primevue#4844](https://github.com/primefaces/primevue/pull/4844)
> > The toggler should not even be shown:
> > image
> 
> Hi, thanks for your reference but I don’t think that remove the empty space or remove the icon is a good idea. I think it should always show the sub-items menu and the icon if there is a items prop given, even it is empty, Sometimes user may want to show an empty list. If they don’t want the list, they should not add the items props. Another way, maybe adding a tip text on the empty place is the best way to solve this problem. So this pr should be **closed**.

That’s mean

With `items` props but empty list:
Should show an empty space or show with some text like “This list is empty.”

With no `items` props but border changed when click:
This should be fixed like my Pull Request in primevue https://github.com/primeface/primevue/pull/4844

**Review by dy-xiaodong2022 — COMMENTED** [review]
This change shouldn’t be merged or accepted.

**Comment by akshayaqburst** [comment]
@melloware Can I do a fix as per your comment? I see the other person's PR is not merged, so not sure if I should follow his comment. Let me know, thanks.

**Comment by melloware** [comment]
I will fix it.

**Pull request closed without merging**
