### PR TITLE
fix #6211 DataTable Drag to select doesn't work on any page past page…

### LINKED ISSUE #6211: DataTable 10.5.3: Drag to select doesn't work on any page past page 1 when paginated
### Describe the bug

Drag to select on a datatable with paginated rows doesn't allow a drag selection on any page past page one. So if I have 1000 records, with `rows={10}`, and a paginator, if you click to page 2 and attempt to drag to select, drag to select ceases to work.

It will work, however, on page one. See reproducer for more details.

### Reproducer

I have provided two, just to be sure I'm not going crazy, and it doesn't work in either.

https://codesandbox.io/p/sandbox/datatable-selection-problem-gfrxph?file=%2Fsrc%2FApp.tsx%3A6%2C16

https://stackblitz.com/edit/vitejs-vite-tigkbd?file=src%2FApp.tsx

### PrimeReact version

10.5.3 (latest)

### React version

18.x

### Language

TypeScript

### Build / Runtime

Next.js

### Browser(s)

_No response_

### Steps to reproduce the behavior

1. In the reproducer, select any number of rows on page one
2. Move to page two, and attempt to select rows by dragging to select
3. You will see you cannot select rows on page two, or any page past page one by dragging to select

### Expected behavior

Drag to select works on any page, regardless of what page, as it did in 10.5.1

### PR DESCRIPTION
**Pull request by kl-nevermore**
Fix #6211 
Related #6007 

20240322135909_rec_

### CODE REVIEW

**Comment by melloware** [comment]
Can you run the lint formatter please they just updated the Lint rules last night.  Also is this new as the user said it was fine in 10.5.1 and started in 10.5.3 so i wonder what change caused this code to cause the issue?

**Comment by kl-nevermore** [comment]
because fix #5870(released 10.5.2) refactor `selectRange` and did not notice that there was separate logic for `paginator`. We don't need it now

**Comment by kl-nevermore** [comment]
after run `npm run lint:fix` make 600 changes were generated, should I push?

**Comment by melloware** [comment]
actually NO leave your PR as is i will submit the fix with the 600 files 😄

**Comment by melloware** [comment]
actually @kl-nevermore yes please submit yours with all the fixes!

**Comment by kl-nevermore** [comment]
emm
There are still many files that failed  after lint:fixed
image

**Comment by melloware** [comment]
yeah let me ping PrimeTek.

**Comment by melloware** [comment]
PrimeTek is going to disable the rule in the build, slowly fix all the issues and then re-enable it once they are all fixed.  So this PR is fine.

**Pull request merged**
