### PR TITLE
Fix:#6141:DataTable:Column: onCellEditComplete is fired twice

### LINKED ISSUE #5556: DataTable: Error when updating a cell
### Describe the bug

I've got the below console error when updating a cell

image

**Minimal code reproduction**:

```js
export default function PrimeDataTable() {
  const [data, setData] = React.useState([
    {
      value: '2',
    },
  ]);
  return (
    <DataTable value={data}>
      <Column
        field="value"
        editor={options => (
          <input
            value={options.value}
            onChange={event => options.editorCallback?.(event.target.value)}
          />
        )}
        onCellEditComplete={({ newValue }) => {
          setData([{ value: newValue }]);
        }}
      />
    </DataTable>
  );
}
```

### Reproducer

https://codesandbox.io/p/sandbox/primereact-demo-forked-v94dr7?file=%2Fsrc%2FApp.js

### PrimeReact version

10.1.1

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

_No response_

### Steps to reproduce the behavior

1. Use a DataTable with cell edit mode
2. Update a React state inside the onCellEditComplete

### Expected behavior

The error `Cannot update a component` should not be displayed in the console.

### LINKED ISSUE #6019: DataTable: `onCellEditComplete()` called after form's `onSubmit()`
### Describe the bug

When hitting "Enter" to complete a cell's edition, if the table is inside a form, the form is submitted before `onCellEditComplete()` is called, leaving no opportunity to prevent form submission through `event.stopPropagation()`. This is likely due to `onCellEditComplete()` being wrapped with `setTimeout()`, I wonder why:

https://github.com/primefaces/primereact/blob/6cd5730be552e4e1307b9a4205b7df99503b4484/components/lib/datatable/BodyCell.js#L182

### Reproducer

_No response_

### PrimeReact version

10.5.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

_No response_

### Steps to reproduce the behavior

_No response_

### Expected behavior

_No response_

### LINKED ISSUE #6141: DataTable => Column: onCellEditComplete is fired twice
### Describe the bug

`onCellEditComplete` of the `Column` component in the `DataTable` is fired twice on [version 10.5.1](https://stackblitz.com/edit/rb6yv7?file=src%2FApp.tsx)
Can be reproduced with the StackBlitz example directly from the docs.

This was working fine on [version 9.6.4](https://stackblitz.com/edit/react-ipzkmq?file=src%2FApp.js)

### Reproducer

https://stackblitz.com/edit/rb6yv7?file=src%2FApp.tsx

### PrimeReact version

10.5.1

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

_No response_

### Steps to reproduce the behavior

Edit cell, click away and see that the `onCellEditComplete` is called twice.

### Expected behavior

`onCellEditComplete` should be called only once

### PR DESCRIPTION
**Pull request by kl-nevermore**
Fix #6141 
Fix #6019 
Fix #5556

### CODE REVIEW

**Comment by didix16** [comment]
Hey @kl-nevermore,  I think `editingRowDataStateRef.current = getEditingRowData()` should be added after line 522

https://github.com/primefaces/primereact/blob/463ba5c70b80127a535ae31e0f3bf2c00889a524/components/lib/datatable/BodyCell.js#L520-L524

It should also update there the state ref, right?

**Comment by kl-nevermore** [comment]
Yes, I missed this.
Maybe it would be better to use useeffect.

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
@kl-nevermore thanks for this let me know when its ready for review!

**Comment by kl-nevermore** [comment]
@melloware 
I updated code, please review thanks!

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
This is a much better fix and removes the hack i added!

**Pull request merged**
