### PR TITLE
Option to reset sort per column (allowUnsort prop on DataTable)

### PR DESCRIPTION
**Pull request by bassarisse**
Following what was discussed here: https://github.com/primefaces/primereact/issues/179

I added a functionality to remove the sort of a column. This first click sorts by ascending, the second by descending, and the third removes the sort configuration. However, this behavior is enabled only if the prop `allowUnsort` is included, so current usage won't break.

Also, as a side-effect, the modifications resolved a bug in multiple sort mode, where a click on a column header right after clicking another one didn't flip the sort order, but instead fixed it to ascending.

Is this suitable?

### CODE REVIEW

**Comment by salup** [comment]
+1

Merge please.

**Comment by cagataycivici** [comment]
Thank you, no other Prime table have this due to lack of interest in this particular feature, if more users demand it, we'll reconsider, thank you.

**Comment by bassarisse** [comment]
It's really unfortunate we'll have to rely on using a fork for that =(

**Comment by Djuki** [comment]
+1

Please reconsider adding this feature. @cagataycivici @mertsincan

**Pull request closed without merging**
