### PR TITLE
feat: pass standard props to the wrapping element

### LINKED ISSUE #2620: Pass data-testid and other standard element attributes to form components
**I'm submitting a ...**  (check one with "x")
```
[x] feature request
```

**Current behavior**
Many of the form components cannot be identified by using recommended approaches like data-testid or name attributes.

**Expected behavior**
To be able to pass data-testid and other standard element attributes to all form components.

7.2.0

### PR DESCRIPTION
**Pull request by kalinkrustev**
Fixes #2620

### CODE REVIEW

**Comment by kalinkrustev** [comment]
The approach of passing 
```js
{...ObjectUtils.findDiffKeys(this.props, ComponentX.defaultProps)}
```
to the wrapping div/span relies on defaultProps having all the props of `ComponentX` listed there, otherwise some props will be also passed to the wrapping div/span element. I checked if this is so for some of the components and it look is.

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
Nice!

**Comment by mertsincan** [comment]
Hi @kalinkrustev,
Perfect! I've wanted to do this for a long time. I guess now is the time. I will merge this PR after I release version 8.0. Could you please update your PR! I am truly grateful to you ;)

Best Regards,

**Comment by kalinkrustev** [comment]
I opened a new request here #2708

**Pull request closed without merging**
