### PR TITLE
Refactor KeyFilter

### PR DESCRIPTION
**Pull request by melloware**
###Defect Fixes
@mertsincan this uses `event.key` which is much more browser standard than the old `event.which` etc and is much more reliable.

It also allows us to remove all the special Safari and Opera and Mozilla handling this class was doing.

Here is a great Keyboard event viewer: https://w3c.github.io/uievents/tools/key-event-viewer.html

Also its universally supported now: https://caniuse.com/?search=event.key

Its a start of refactoring for #2101

### CODE REVIEW

**Comment by melloware** [comment]
Also it looks like this code originated from PrimeNG so it was proabbly valid a long time ago with these IE and Opera etc fixes none of which should be necessary now.

**Comment by mertsincan** [comment]
@melloware can you create a Github issue?

**Comment by melloware** [comment]
Yep

**Comment by melloware** [comment]
Done!

**Pull request merged**
