### PR TITLE
Fix #6809: Make sure editable dropdown opens when user types

### LINKED ISSUE #6809: Dropdown: does not open OnEditableInputChange
### Describe the bug

If you have an editable dropdown in focus, and you start typing, the dropdown should open automatically. Currently, this does not happen. It will not open if, for example, you type "a", although it will open if you hit the `backspace` key. 

### Reproducer

_No response_

### PrimeReact version

10.6.6.

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

_No response_

### Steps to reproduce the behavior

1. Go to the [editable primereact dropdown](https://primereact.org/dropdown/#editable)
2. Click inside the input field
3. Start typing "paris"
4. Observe as the dropdown does not open, and therefore does not automatically put the option "paris" in focus.
5. Hit the `backspace` key
6. Observe as the dropdown opens.

### Expected behavior

The editable dropdown should open when the user types.

### PR DESCRIPTION
**Pull request by peconomou929**
Fix #6809. 

This bug did not always exist. It was first introduced in #6032.

### CODE REVIEW

**Comment by melloware** [comment]
@peconomou929 can you retest the issue in https://github.com/primefaces/primereact/issues/6027 that caused me to make the original change please?

**Review by melloware — CHANGES_REQUESTED** [review]
I must have had a good reason to make this change

**Comment by peconomou929** [comment]
@melloware I am testing my changes with a dropdown that has `filter=true` and `editable=true` and the issue in #6027 is not present.

**Comment by melloware** [comment]
Nice!  From looking at this code again it has me wondering.  Why don't show() and hide() just check the overlayvisible state instead of everywhere in the code?

Like for example:

```js
const show = () => {
            if (overlayVisibleState) return;

            setFocusedOptionIndex(focusedOptionIndex !== -1 ? focusedOptionIndex : props.autoOptionFocus ? findFirstFocusedOptionIndex() : props.editable ? -1 : findSelectedOptionIndex());
            setOverlayVisibleState(true);
        };
```


I know its not related to your PR but doesn't it make sense that show() and hide() would just check the overlayVisibleState?

**Comment by peconomou929** [comment]
> Nice! From looking at this code again it has me wondering. Why don't show() and hide() just check the overlayvisible state instead of everywhere in the code?

Hmm, I see your point. It might make sense to do that, but I'm not entirely sure it's a good idea (for now at least). For example, the `hide` function is

```
const hide = () => {
    setOverlayVisibleState(false);
    clickedRef.current = false;
};
```

In addition to setting the visible state, it also sets the `clickedRef`. What if somebody calls the `hide` function (perhaps one of the current usages of `hide`) and expects the `clickedRef` to always be set to false?

**Comment by melloware** [comment]
ok i will take a look!

**Pull request merged**
