### PR TITLE
Fix #5349: PanelMenu fix from PrimeVue

### LINKED ISSUE #5349: PanelMenu: Menu items with no sub-items toggling border
### Describe the bug

PanelMenu: Menu items with no sub-items toggling border

### Reproducer

_No response_

### PrimeReact version

10.1.0

### React version

17.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

_No response_

### Steps to reproduce the behavior

1. Go to Panel Menu
2. Use a basic Panel Menu in your project
3. Try building a menu item which has no sub items present in it.
4. Click on the newly created menu item which has no sub items.
5. It shows an empty space .

image

### Expected behavior

Menu items with no sub-items should not toggle.

After fix - 
image

### PR DESCRIPTION
**Pull request by melloware**
Fix #5349: PanelMenu fix from PrimeVue

Ported fix from PrimeVue: https://github.com/primefaces/primevue/pull/4844/files

### CODE REVIEW

**Comment by akshayaqburst** [comment]
@melloware I would have worked on it!

**Comment by akshayaqburst** [comment]
@melloware I just cloned this locally, and I did not see this working. Were you able to get the issue fixed with this change?

**Comment by melloware** [comment]
Let me try your exact example

**Comment by melloware** [comment]
Yes so...

```json
{
            label: 'Edit',
            icon: 'pi pi-fw pi-pencil',
            items: []
        },
```

Looks like this..
image

And if you remove `item: []` like this..

```json
        {
            label: 'Edit',
            icon: 'pi pi-fw pi-pencil',
        },
```

image


Which is what @dy-xiaodong2022  is saying is the correct behavior. This fixes an extra border radius from being generated on an item with no values.

**Review by dy-xiaodong2022 — APPROVED** [review]

**Pull request merged**
