### PR TITLE
Fix #5858: Update focus index on menu item hover

### LINKED ISSUE #5858: Menu: first menu item selected on popup
### Describe the bug

If I create a menu component with submenu headers and menu items, then clicking on any of the submenu headers will activate the first menu item in the menu. This is shown in the image, taken directly from the PrimeReact website.

Screenshot 2024-01-30 at 7 04 27 PM

Take a look at the steps to reproduce the behaviour below.

### Reproducer

https://primereact.org/menu/#popup

### PrimeReact version

10.3.3

### React version

18.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

_No response_

### Steps to reproduce the behavior

1. Go to [this subheading](https://primereact.org/menu/#group) of the documentation for the PrimeReact Menu.
2. In the example, click on the header "Profile."
3. Observe as the menu item "New" is activated (given a background color).

You will see two changes associated with this in the HTML:
1. if you look at the menu item "New," the attribute "data-p-focused" is set to true.
2. if you look at the whole menu element, it is given an attribute "aria-activedescendants". 

### Expected behavior

In the menu component, a menu items is activated only when the user clicks on the item itself.

### PR DESCRIPTION
**Pull request by bogue**
Fix [#5858](https://github.com/primefaces/primereact/issues/5858): Update focus index on menu item hover

### CODE REVIEW

**Comment by melloware** [comment]
Please run `npm run format`

**Review by melloware — CHANGES_REQUESTED** [review]
Formatting issues

**Review by melloware — APPROVED** [review]

**Comment by mertsincan** [comment]
I agree with Melloware's comments regarding accessibility in the issue. Also, we cannot add this enhancement by default. It can be a prop option. Finally, I think you can create a discussion ticket to collect feedback from other users.

For now, closed. Thanks a lot for your understanding!

**Comment by bogue** [comment]
@mertsincan: I must be missing something here, from my standpoint, @melloware is the one who reopened the issue, as well as reviewed and approved this PR; I fail to see any disagreement here. And as mentioned in the ticket, the proposed behavior is in-line with ARIA guidelines. Anyway, no biggie regardless. Thanks for the feedback!

**Comment by melloware** [comment]
@mertsincan i think you should take another look at this one as it follows more closely accessibility guidelines...

**Pull request closed without merging**
