### PR TITLE
fix: RadioButton: data selector and Hook Form doc

### LINKED ISSUE #5679: RadioButton: data selector and Hook Form doc display error
### Describe the bug

```tsx
 const isRadioToggled = radioClicked && (DomHandler.hasClass(elementRef.current, 'p-radiobutton-checked') === checked ? !checked : false);
``` 
20240104124236_rec_

### Reproducer

https://primereact.org/radiobutton/#hookform

### PrimeReact version

master

### React version

18.x

### Language

TypeScript

### Build / Runtime

Create React App (CRA)

### Browser(s)

_No response_

### Steps to reproduce the behavior

_No response_

### Expected behavior

_No response_

### PR DESCRIPTION
**Pull request by kl-nevermore**
Fix #5679

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
Looks like some changes underneath of you and there is a conflict now.

**Comment by melloware** [comment]
Can you also check I bet `Checkbox` has a similar issue?

**Review by melloware — CHANGES_REQUESTED** [review]
See feedback

**Comment by kl-nevermore** [comment]
Okay, I will check it  tomorrow
tonight, power outage at home

**Comment by kl-nevermore** [comment]
I checked code and doc, Checkbox no problem

`DomHandler.hasClass(elementRef.current, 'p-radiobutton-checked')` added by https://github.com/primefaces/primereact/pull/3637

Checkboxes don't have this problem #3636

**Review by melloware — APPROVED** [review]

**Pull request merged**
