### PR TITLE
Fix #7110 - SpeedDial : Fix aria-controls values

### LINKED ISSUE #7110: SpeedDial : Fix aria-controls values
### Describe the bug

"The aria-controls attribute identifies the element (or elements) whose contents or presence are controlled by the element on which the attribute is set" (--> https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-controls)

The aria-controls attribute should only be placed on the SpeedDial trigger button. And its value must be the identifier or list of identifiers of its items.

**Current behavior :**
image

### Reproducer

_No response_

### System Information

```Shell
"primereact": "10.8.2"
"react": "^18.2.0"
```

### Steps to reproduce the behavior

_No response_

### Expected behavior

The aria-controls value should be an actual id (or a list of ids)

image

### PR DESCRIPTION
**Pull request by kyybo**
"The aria-controls attribute identifies the element (or elements) whose contents or presence are controlled by the element on which the attribute is set" (--> https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-controls)

The aria-controls attribute should only be placed on the SpeedDial trigger button. And its value must be the identifier or list of identifiers of its items.

Fix #7110

### CODE REVIEW

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
can you run `npm run format` to format the code please.

**Comment by melloware** [comment]
Its still failing the format check `npm run format:check` it looks like it formatted too much now?  It should just fix your file if you run `npm run format` from the root project.

**Comment by kyybo** [comment]
Sorry this is my first PR, I'm not familiar with all the procedures yet.
As I edited the file directly from github I couldn't run the `npm run format` command. But I'm gonna make it 😅

**Comment by melloware** [comment]
ok now run `npm run lint:fix` it has some lint errors.

**Pull request merged**
