### PR TITLE
Feature: "notIn" mode for Datatable filters

### LINKED ISSUE #5450: Datatable: "not-in" mode for filter function
### Discussed in https://github.com/orgs/primefaces/discussions/571

<div type='discussions-op-text'>

<sup>Originally posted by **dnyaneshwar2023** November 28, 2023</sup>
Hello folks 👋 ,

Do you guys think we should also have "not-in"/"notIn" mode for the filter function that is used from the component reference for the DataTable?

https://primereact.org/datatable/#api.DataTable.methods
image

I was using it in one of my projects and I was hoping this mode to have since there can be use case where I have use case to avoid some items. (That could be achieved through providing all items except that we want to avoid in "in" mode but that seems hacky when I don't have the whole list of data)

I am happy to contribute on it if it's needed.</div>

### PR DESCRIPTION
**Pull request by dnyaneshwar2023**
Fix #5450

### CODE REVIEW

**Comment by dnyaneshwar2023** [comment]
Hi Team,
Since I introduced "notIn" filter in FilterService, should I update type declarations for following components as well?
I have updated it for DataTable.

**Components using FilterService:**
DataTable
Dropdown
ListBox
Multiselect
OrderList
PickList
TreeTable

**Comment by melloware** [comment]
Yes I think it should be updated anywhere filters are defined.

**Comment by dnyaneshwar2023** [comment]
> Yes I think it should be updated anywhere filters are defined.

I added it in the following components since they were using "in" matchMode so it makes sense to add "notIn" there.
- TreeTable
- Column
- PickList

**Comment by dnyaneshwar2023** [comment]
@melloware I am not sure, why this was closed. I didn't got why pull request #5460 mentioned while closing this, looks like it's not related to this pull request.

**Comment by melloware** [comment]
It was accidental.

**Comment by dnyaneshwar2023** [comment]
> It was accidental.

Ok, Thanks for reopening.

**Comment by mertsincan** [comment]
Thanks a lot for your contribution!

**Pull request merged**
