### PR TITLE
feat:#5327:CascadeSelect:add panelHeaderTemplate for cascadeselect

### PR DESCRIPTION
**Pull request by kl-nevermore**
### Feature Requests
feat:#5327:CascadeSelect:add panelHeaderTemplate for cascadeselect

### CODE REVIEW

**Review by melloware — CHANGES_REQUESTED** [review]
Not sure I agree with this change. This component doesn't have a header in the other prime libs Vue or NG does it?

What is the purpose of a header?

**Comment by kl-nevermore** [comment]
Custom headers, such as treeselect and dropdown, to accommodate custom search and other functions

**Comment by melloware** [comment]
Yes but those have a built in filter mechanism: https://primereact.org/treeselect/#filter  IT makes no sense for CascadeSelect?  I am just wondering what your use case is?

**Comment by melloware** [comment]
It would also be missing `panelClassName` and `panelFooterTemplate` as well if you are trying to make it like TreeSelect or Dropdown no?

**Comment by kl-nevermore** [comment]
> It would also be missing `panelClassName` and `panelFooterTemplate` as well if you are trying to make it like TreeSelect or Dropdown no?

### You're right I didn't consider other scenarios, this PR is not complete



> Yes but those have a built in filter mechanism: https://primereact.org/treeselect/#filter IT makes no sense for CascadeSelect? I am just wondering what your use case is?

### when I use it normally, I need multiple panels 
image


### when search i can combine itemsTemp to impl my case
image

**Pull request closed without merging**
