### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by francesco-strazzullo**
I've Installed [Enzyme](https://github.com/airbnb/enzyme): a test utility for React in order to test how components interact with DOM. I also created two simple tests for the Button component as an example. I think that it would be cool to have a complete test suite for the PrimeReact components.

### CODE REVIEW

**Comment by cagataycivici** [comment]
@mertsincan Can you add the test for Button?

**Comment by francesco-strazzullo** [comment]
@cagataycivici @mertsincan I fixed conflicts and updated dependencies. If you can merge this I could help with tests

**Comment by cagataycivici** [comment]
Will merge manually, thank you.

**Comment by arun-sahaj** [comment]
Is there unit tests for all the components? 

I haven't seen any test cases written for all the components and it is difficult to write test cases for implementing components like autocomplete

**Comment by melloware** [comment]
No not all components have tests yet.

**Pull request closed without merging**
