### PR TITLE
Fix #6068: Documentation Fixes

### LINKED ISSUE #6068: Sidebar: "Pass Through" documentation corrections
### Describe the bug

Discussion : https://github.com/orgs/primefaces/discussions/1332

Option number three (3), five (5), and (6) under the Sidebar PT Options section do not match with the Wireframe.

1. Option 3 is not "closeButtonIcon" 🤔.
2. Option 4 should be  "icons".
3. Option 5 should be  "closeIcon".
4. Option 6 should be "content".

Screen Shot 2024-02-29 at 3 45 20 PM

Screen Shot 2024-02-29 at 3 49 00 PM

I would love to raise a PR for this issue. 

### Reproducer

_No response_

### PrimeReact version

10.1.1

### React version

18.x

### Language

ALL

### Build / Runtime

Create React App (CRA)

### Browser(s)

_No response_

### Steps to reproduce the behavior

1. Go to the Documentation Components section.
2. Find the Sidebar component.
3. Go to the Pass Through tab.
4. See the Sidebar PT Options do not match with the Wireframe.

### Expected behavior

_No response_

### PR DESCRIPTION
**Pull request by charithAmila**
Defect Fixes

Fixed #6068 Sidebar "Pass Through" documentation issue.
Fix: #6070
Fix: #6078 

Screen Shot 2024-02-29 at 3 45 20 PM

Screen Shot 2024-02-29 at 3 49 00 PM

Options 3,4,5 and 6 did not match with the Wireframe. 
I fixed the 4,5 and 6 mismatching with this PR. 

Current preview: 
Screen Shot 2024-03-01 at 12 20 35 AM

### CODE REVIEW

**Comment by melloware** [comment]
How did you do this did you edit this file? It is auto generated i think the main SideBarbase.js has to be updated?

**Comment by melloware** [comment]
Actually you have to fix the order in `sidebar.d.ts` then it will re-generate the docs in that order.

**Review by melloware — CHANGES_REQUESTED** [review]
See comments

**Comment by charithAmila** [comment]
> Actually you have to fix the order in `sidebar.d.ts` then it will re-generate the docs in that order.

Thank you very much. I will update the PR.

**Comment by melloware** [comment]
after you make the changes to `.d.ts` then run `npm run build:api` that will regenerate the index.json from your TS changes.

**Review by melloware — APPROVED** [review]

**Comment by charithAmila** [comment]
Hi @melloware 
I fixed options 4,5 and 6. 

I am not sure about option 3 in the wireframe. Before modifying the "Sidebar PT Options" I think it should update the wireframe.

Screen Shot 2024-03-01 at 9 57 38 AM

**Comment by melloware** [comment]
The wireframe is out of our control PrimeTek does that. The best we can do is fix the TS docs...

**Comment by charithAmila** [comment]
I got it. Thank you very much for approving the PR.

**Review by nitrogenous — APPROVED** [review]

**Comment by nitrogenous** [comment]
Thank you for your contribution. We are actually thinking about a new system for more dynamic wireframes. We are open for ideas.

**Comment by charithAmila** [comment]
You are welcome. I look forward to more contributions.

**Pull request merged**
