### PR TITLE
Support for React Form libraries

### PR DESCRIPTION
**Pull request by rodriguezc**
###Defect Fixes
PrimeReact input events are not compatible with React forms libraries. (#537 )
This PR normalize Prime React input events

### CODE REVIEW

**Comment by cagataycivici** [comment]
Is it possible to resolve the conflicts?

**Comment by cagataycivici** [comment]
Also please drop formik demo, we don't need that in the showcase. Then we'll merge.

**Comment by cagataycivici** [comment]
Also is there a standard on these form libraries on how to integrate with 3rd party UI suites, this PR seems to be tuned only for formik, do we need to change code again for another library, why do we need to change code on our side?

**Comment by rodriguezc** [comment]
Managing forms is really verbose in react. 

It quickly becomes necessary to integrate a React form library.
Best form libraries for React are):
-Formik
-Final Form
-React-redux-form

These libraries implements a default onChange and onBlur handler.
All of them check value in "e.target.value",

React-redux-form also check if event has stopPropagation and preventDefault before getting the value in e.target.value. Otherwise the value is the event object itself. In case of primereact it will be {e: value} 

It's possible to override their implementation in order to be compatible with Prime React. Everyone who use Prime React and a Form library needs to make this override.

Example of default Final Form onChange override (onChange is setted with {...input} but then overrided):
https://codesandbox.io/s/40mr0v2r87 

It think that it could be much better if Prime React is compatible with these default handlers.

Formik default implementation of onChange can be found there:
https://github.com/jaredpalmer/formik/blob/master/src/Formik.tsx#L287

Redux form default implementation of onChange can be found there:
https://github.com/davidkpiano/react-redux-form/blob/afa9a9680c426fd745d35e4edd360e36d3439557/src/utils/get-value.js#L31

Final form default implementation of onChange can be found there:
https://github.com/final-form/react-final-form/blob/master/src/Field.js#L117

I removed the Formik demo in the show case and make my PR compatible with these 3 libraries.

I also created a branch to test the compatibility with Formik, Redux and Final Form for each of these libraries:
https://github.com/rodriguezc/primereact/tree/formlibs

**Comment by cagataycivici** [comment]
Thank you, will review later today as soon as beta.4 dev starts.

**Comment by cagataycivici** [comment]
Sorry, could you please update it to support the new Spinner.

**Comment by rodriguezc** [comment]
That's done and ok for me.
But, there is a problem with actual AutoComplete implementation: If it's value is updated from props, the visible input value is not updated. I found it when trying to reset the form. 
In this case, React Form libraries update components props with initial form values.
https://github.com/rodriguezc/primereact/tree/formlibs2

**Comment by cagataycivici** [comment]
Thank you, we'll get into it this week.

**Comment by cagataycivici** [comment]
Merged, thank you very much, AutoComplete case is fixed by the way.

https://github.com/primefaces/primereact/issues/576

**Comment by raDiesle** [comment]
Merge?

**Comment by rahulsale** [comment]
Is this available into the PrimeReact Library and is there any documentation of the same ?

**Comment by moviapp** [comment]
@rahulsale Had any success integrating Primefaces with Formik? Found any documentation?
Having a hard time here...

**Comment by shayegh** [comment]
Hi,
may you give some examples of how this works?

**Pull request merged**
