### PR TITLE
Feat: Stateful TreeTable

### LINKED ISSUE #6385: Stateful TreeTable?
### Discussed in https://github.com/orgs/primefaces/discussions/1329

<div type='discussions-op-text'>

<sup>Originally posted by **MBelniak** February 29, 2024</sup>
DataTable can save its configuration in session/local storage https://primereact.org/datatable/#stateful
How difficult would it be to implement the same functionality in TreeTable? I assume most of the logic can be borrowed form the DataTable.</div>

### PR DESCRIPTION
**Pull request by MBelniak**
As discussed here https://github.com/orgs/primefaces/discussions/1329#discussioncomment-8647981
@melloware 

I copied most of the code from DataTable with some adjustments wherever they were needed. I see there's lots of duplicated code between TreeTable and DataTable, but I don't see any shared location designated for that.

Fix #6385

### CODE REVIEW

**Comment by melloware** [comment]
@MBelniak I opened a ticket and linked it!

**Comment by MBelniak** [comment]
@melloware when do you think you or someone from the team will be able to do a review?

**Comment by melloware** [comment]
@MBelniak there is no timeline.,  If you need this feature i suggest your organization look to financially sponsor it through PrimeReact PRO support: https://primereact.org/support/

**Review by nitrogenous — APPROVED** [review]
LGTM

**Comment by nitrogenous** [comment]
We appreciate your contribution and thank you for your patience. As we are currently working on the next-generation version of PrimeReact, the implementation of new features has been temporarily paused and may take some time.

**Comment by nitrogenous** [comment]
We appreciate your contribution and thank you for your patience. As we are currently working on the next-generation version of PrimeReact, the implementation of new features has been temporarily paused and may take some time. @MBelniak

**Pull request merged**
