### PR TITLE
Fix #2745: Multiselect inline flex

### LINKED ISSUE #2745: MultiSelect: Enable more display options
**I'm submitting a ...**  (check one with "x")
```
[x ] feature request
```

- Be able to display the MultiSelect panel inline
- Control the layout of items
- Be able to pass className for items via the component properties

**Please tell us about your environment:**

* **PrimeReact version:**
8.0.0-rc.1

### PR DESCRIPTION
**Pull request by kalinkrustev**
Add `inline`, `flex` and `itemClassName` properties for `MultiSelect`, to control the panel display and make it possible to render it inline or apply flex layout to it.

image
image

Fix #2745

### CODE REVIEW

**Comment by melloware** [comment]
Excellent PR. Can you please open a matching issue so I can link the PR to a ticket?

**Comment by kalinkrustev** [comment]
Fix #2745

**Comment by kalinkrustev** [comment]
Done

**Review by melloware — APPROVED** [review]

**Comment by mertsincan** [comment]
Hi @kalinkrustev,

Thanks a lot for this great feature! We will evaluate this after the 8.0.Final. If the team approves this PR, we will also add this feature to PrimeVue and PrimeNg.

**Comment by kalinkrustev** [comment]
When components were based on classes, I was able to achieve this functionality by subclassing and overriding some methods, but now I can't. I hope it can be accepted.

**Comment by kalinkrustev** [comment]
Hi @mertsincan, what do you mean with "after 8.0.Final" ? I see the issue #2745 was assigned to the 9.0.0 milestone.

**Comment by melloware** [comment]
@kalinkrustev do you mind rebasing this PR?

**Comment by kalinkrustev** [comment]
Yes, I will rebase it. I hope next Monday I will be able to do this.

**Comment by kalinkrustev** [comment]
Rebasing was hard, so I made manually the same modifications on top of master.

**Pull request merged**
