### PR TITLE
Feat #6589 return option when optionValue is empty

### LINKED ISSUE #6589: Dropdown: Init-Value not working if options have label,value properties
### Describe the bug

If Dropdown is filled with `{label: string, value: any}[]` the inital value isn't selected.

### Reproducer

https://stackblitz.com/edit/vitejs-vite-2prkbq?file=src%2FApp.tsx

### PrimeReact version

10.6.5

### React version

18.x

### Language

ALL

### Build / Runtime

Vite

### Browser(s)

_No response_

### Steps to reproduce the behavior

_No response_

### Expected behavior

_No response_

### PR DESCRIPTION
**Pull request by KirilCycle**
### Defect Fixes
Fix #6589

Similar to primevue, returns the entire option object if the desired optionValue is missing

### CODE REVIEW

**Comment by melloware** [comment]
cc @Rekl0w i don't think this is the correct fix.

**Comment by Rekl0w** [comment]
No it's not. @melloware

**Comment by sja-cslab** [comment]
I'm confused now.
#6518 is about `optionLabel` as your fix in #6520 
but this fix here is about `optionValue`.

**Comment by melloware** [comment]
@sja-cslab you can see label and value do the same things..

```js
        const getOptionLabel = (option) => {
            return props.optionLabel ? ObjectUtils.resolveFieldData(option, props.optionLabel) : ObjectUtils.resolveFieldData(option, 'label') || option;
        };

        const getOptionValue = (option) => {
            return props.optionValue ? ObjectUtils.resolveFieldData(option, props.optionValue) : ObjectUtils.resolveFieldData(option, 'value') || option;
        };
```

**Comment by sja-cslab** [comment]
@melloware sure I noticed that but thought @Rekl0w tried to roll that back - just asking because that would fix the issue #6589 I guess.

**Pull request closed without merging**
