### PR TITLE
Fix #2532 InputNumber fix, fixed inputnumber to dont accept put letter on input

### LINKED ISSUE #2532: InputNumber accepting letters and deleting previus value
### There is no guarantee in receiving an immediate response in GitHub Issue Tracker, If you'd like to secure our response, you may consider *PrimeReact PRO Support* where support is provided within 4 business hours

**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://forum.primefaces.org/viewforum.php?f=57
```

**Codesandbox Case (Bug Reports)**

https://codesandbox.io/s/primereact-test-forked-i946f?file=/src/index.js

**Current behavior**
When use the InputNumber and try input a letter

**Expected behavior**
Never appear a letter on InputNumber

**Minimal reproduction of the problem with instructions**

Create a InputNumber, set a min and then try to input a number value and then input any letter

https://codesandbox.io/s/qjx332qq4

Please tell us about your environment:
Windows 10
node 16.13.0
react 17.0.2
primeReact 7.0.1

React version:
react 17.0.2

PrimeReact version:
primeReact 7.1.0

Browser:

[ Chrome XX ]

Language: [ES6/7]

### PR DESCRIPTION
**Pull request by IHPNULL**
###Defect Fixes
#2532 
###Feature Requests
Due to company policy, we are unable to accept feature request PRs with significant changes as such cases has to be implemented by our team following our own processes.
Smaller scaled feature implementations such as adding a property to a component will be considered for merging.

### CODE REVIEW

**Comment by melloware** [comment]
This won't handle special chars like accent and umlaut right?

```
à, è, ì, ò, ù,

ã, ñ, õ

ä, ë, ï, ö, ü, ÿ,
```

**Comment by IHPNULL** [comment]
> This won't handle special chars like accent and umlaut right?
> 
> ```
> à, è, ì, ò, ù,
> 
> ã, ñ, õ
> 
> ä, ë, ï, ö, ü, ÿ,
> ```

u're right, i'm going to fix it

**Comment by IHPNULL** [comment]
I already did the fix, please review asap  🙂

**Comment by melloware** [comment]
I just checked it with Regex101 here: https://regex101.com/r/62wB81/1/

Looks good to me!

**Review by melloware — APPROVED** [review]

**Comment by IHPNULL** [comment]
WOW u're fast shuashuahusahuashuahsuha

**Comment by melloware** [comment]
This is what code reviews are for 😄

**Comment by IHPNULL** [comment]
issue fixed

**Pull request closed without merging**
