### PR TITLE
Update toast to always have up to date messages state

### PR DESCRIPTION
**Pull request by omerts**
Fixes bug https://github.com/primefaces/primereact/issues/2668

### CODE REVIEW

**Review by melloware — APPROVED** [review]
Looks good to me just wasnt' sure if PrimeTek had it in the `state` for a reason.  But your fix looks good to me.

**Comment by omerts** [comment]
@melloware I presume that he had it on state in order to cause renders when this state changes, so instead I used forceUpdate for rendering on changes.

**Comment by melloware** [comment]
Excellent @omerts   Do you see my suggestion about adding a `replace` method as well like Mssages has so you can call it and it will call clear() and then show() for the new message?

```ts
public replace(message: ToastMessageType): void;
```

**Comment by omerts** [comment]
@melloware done :)

**Comment by melloware** [comment]
Can you also update the .d.tams file to list this new replace method.  Thanks!

**Review by melloware — CHANGES_REQUESTED** [review]
See my comment about the TypeScript definition update.

**Review by melloware — APPROVED** [review]

**Comment by melloware** [comment]
There are merge conflicts to fix.

**Comment by melloware** [comment]
@omerts do you mind updating your fixes?

**Comment by melloware** [comment]
This is fixed now that hooks are being used: https://codesandbox.io/s/primereact-test-forked-5zuel3

**Comment by omerts** [comment]
@melloware  Sorry for not getting back to this. Happy to know it is fixed, you are awesome!

**Pull request closed without merging**
